<?php

namespace App\Filament\Resources\NoticeboardResource\Pages;

use App\Filament\Resources\NoticeboardResource;
use Closure;
use Filament\Pages\Actions\CreateAction;
use Filament\Resources\Pages\ListRecords;

class ListNoticeboards extends ListRecords
{
    protected static string $resource = NoticeboardResource::class;

    protected function getActions(): array
    {
        return [
            CreateAction::make()
                ->visible(auth()->user()->can('Create notice')),
        ];
    }

    protected function getTableRecordUrlUsing(): ?Closure
    {
        return null; //parent::getTableRecordUrlUsing(); // TODO: Change the autogenerated stub
    }
}
